### ISSUE TITLE
 Property 'forRoot' does not exist on type 'typeof ShopifyCoreModule'.

### ISSUE THREAD

**Issue by shuffle25** [nestjs-shopify/nestjs-shopify#180]
What is the reason for this error？
 Property 'forRoot' does not exist on type 'typeof ShopifyCoreModule'.
```
import { Module } from '@nestjs/common';
import { ShopifyCoreModule } from '@nestjs-shopify/core';
import { ShopifyAuthModule } from '@nestjs-shopify/auth';
import { ApiVersion } from '@shopify/shopify-api';

@Module({
  imports: [
    ShopifyCoreModule.**forRoot**({
      apiKey: 'foo',
      apiSecret: 'bar',
      apiVersion: ApiVersion.Unstable,
      hostName: 'localhost:8081',
      isEmbeddedApp: true,
      scopes: ['test_scope'],
    }),
  ],
})
export class ShopifyModule {}
```
log：
```
src/system/EC/shopify.module.ts:8:23 - error TS2339: Property 'forRoot' does not exist on type 'typeof ShopifyCoreModule'.
api  | 
api  | 8     ShopifyCoreModule.forRoot({
api  |                         ~~~~~~~
api  | 
api  | Found 1 error(s).
api  | 
api  | /app/node_modules/@nestjs-shopify/core/src/core.module-builder.js:6
api  | _a = new common_1.ConfigurableModuleBuilder()
api  |      ^
api  | 
api  | TypeError: common_1.ConfigurableModuleBuilder is not a constructor
api  |     at Object.<anonymous> (/app/node_modules/@nestjs-shopify/core/src/core.module-builder.js:6:6)
api  |     at Module._compile (node:internal/modules/cjs/loader:1191:14)
api  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
api  |     at Module.load (node:internal/modules/cjs/loader:1069:32)
api  |     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
api  |     at Module.require (node:internal/modules/cjs/loader:1093:19)
api  |     at require (node:internal/modules/cjs/helpers:108:18)
api  |     at Object.<anonymous> (/app/node_modules/@nestjs-shopify/core/src/index.js:7:29)
api  |     at Module._compile (node:internal/modules/cjs/loader:1191:14)
api  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
api exited with code 1
```

package json
```
"@nestjs/common": "^7.0.0",
"@nestjs-shopify/auth": "^3.1.0",
"@nestjs-shopify/core": "^2.1.0",
"@shopify/shopify-api": "^6.2.0",
```

**Comment by tolgap** [comment]
You need at least NestJS `v9.0.0`

**Comment by tolgap** [comment]
Closing as this lib only supports Nest > 9.0
