### ISSUE TITLE
Error: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: ****.myshopify.com

### ISSUE THREAD

**Issue by Lolek381** [nestjs-shopify/nestjs-shopify#325]
Hey so first of all thanks you for this amazing library!
Shopify app is skyrocketing, nevr the lees from time to time we get the following error:
`[shopify-api/INFO] Completing OAuth | {shop: ****.myshopify.com}
[shopify-api/ERROR] Could not find OAuth cookie | {shop: ****.myshopify.com}
Error: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: ****.myshopify.com
at Object.<anonymous> (/app/node_modules/@shopify/shopify-api/lib/auth/oauth/oauth.js:75:23) 
at Generator.next (<anonymous>) 
at fulfilled (/app/node_modules/tslib/tslib.js:164:62)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by tolgap** [comment]
@Lolek381 thanks for the kind words! Where are you redirecting users to after:

- Offline auth
- Online auth

?

**Comment by Lolek381** [comment]
Well so as i understand this error is happening even before the AfterAuthHandlerService, my auth module looks like this:
`@Module({
  imports: [
    ShopifyAuthModule.forRootAsyncOffline({
      imports: [AuthHandlerModule],
      useFactory: (afterAuthHandler: AfterAuthHandlerService) => ({
        basePath: 'shop',
        afterAuthHandler,
      }),
      inject: [AfterAuthHandlerService],
    }),
    ShopifySessionModule,
  ],
})
export class ShopifyAuthConfigModule {}
`
 And it calls the AfterAuthHanlderService which creates some stuff in the DB and then redirects the user to the front end, already logged in, the error happens  just before that beacause nothing is creted in the DB, and no log occurs, what is the  OAuth cookie? this behaviour is completely random, it only happens 3-5% of our installs.

**Comment by tolgap** [comment]
@Lolek381 you have to also use online auth. You use offline auth to install the app, and then redirect to the online auth to receive a temporary token. This is how every example of Shopify docs explain it as well. I wouldn't deviate from that structure.

Here's an example app to draw inspiration from: https://github.com/nestjs-shopify/example-nx-app

**Comment by Lolek381** [comment]
@tolgap i will have a look onto this, will get back with more insights to see if we can close this thread! thanks in advance

**Comment by tolgap** [comment]
@Lolek381 did you have any news on this? 🙂
