### ISSUE TITLE
How to use ShopifyAuthGuard with GraphQL?

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [nestjs-shopify/nestjs-shopify#441]
Hi! I'm trying to use this package for my shopify backend where I need to make few GQL resolvers only for authenticated users.
So far I get the error like so:

## Error
```json
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'headers')",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["protectedQueryOnline"],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "TypeError: Cannot read properties of undefined (reading 'headers')",
          "    at ShopifyExpressAdapter.extractHeaders (/Users/****/GitHub/shopify-server/packages/express/src/http/express.http-adapter.ts:26:20)",
          "    at ShopifyExpressAdapter.getHeadersFromExecutionContext (/Users/****/GitHub/shopify-server/packages/core/src/http/http.adapter.ts:81:17)",
          "    at ShopifyExpressAdapter.getHeaderFromExecutionContext (/Users/****/GitHub/shopify-server/packages/core/src/http/http.adapter.ts:71:26)",
          "    at getSessionTokenFromAuthHeader (/Users/****/GitHub/shopify-server/packages/auth/src/utils/get-session-token-from-request.util.ts:18:39)",
          "    at getSessionTokenFromRequest (/Users/****/GitHub/shopify-server/packages/auth/src/utils/get-session-token-from-request.util.ts:9:5)",
          "    at getShopFromSessionToken (/Users/****/GitHub/shopify-server/packages/auth/src/utils/get-shop-from-request.util.ts:33:43)",
          "    at getShopFromRequest (/Users/****/GitHub/shopify-server/packages/auth/src/utils/get-shop-from-request.util.ts:14:5)",
          "    at ShopifyAuthGuard.<anonymous> (/Users/****/GitHub/shopify-server/packages/auth/src/auth.guard.ts:47:36)",
          "    at Generator.next (<anonymous>)",
          "    at fulfilled (/Users/****/GitHub/shopify-server/node_modules/tslib/tslib.js:166:62)"
        ]
      }
    }
  ],
  "data": null
}

```

## Query
```gql
query Query {
  protectedQueryOnline
}

```

## Failing resolver

```ts
import {
  CurrentSession,
  ShopifyAuthGuard
} from '@nestjs-shopify/auth'
import { UseGuards } from '@nestjs/common'
import { Args, Mutation, Query, Resolver } from '@nestjs/graphql'
import { Session } from '@shopify/shopify-api'
import { FavouriteDesignCreateInput } from '@src/generated/favourite-design/favourite-design-create.input'
import { FavouriteDesignUpdateInput } from '@src/generated/favourite-design/favourite-design-update.input'
import { FavouriteDesignWhereInput } from '@src/generated/favourite-design/favourite-design-where.input'
import { FavouriteDesign } from '@src/generated/favourite-design/favourite-design.model'
import 'reflect-metadata'
import { FavouriteDesignByIdInput } from './dto'
import { FavouriteDesignService } from './service'

@Resolver()
export class FavouriteDesignResolver {
  constructor(private favouriteDesignService: FavouriteDesignService) {}

  @UseGuards(ShopifyAuthGuard)
  @Query(() => String)
  protectedQueryOnline(@CurrentSession() session: Session): string {
    console.log(session)
    return `Protected query for shop: ${session.shop}`
  }

 //...rest of the code...
```

## Main app `app.module.ts`
```ts
import { ApolloServerPluginLandingPageLocalDefault } from '@apollo/server/plugin/landingPage/default'
import { InMemoryLRUCache } from '@apollo/utils.keyvaluecache'
import { configuration } from '@config/configuration'
import { AuthStrategy, ShopifyAuthModule } from '@nestjs-shopify/auth'
import { ShopifyExpressModule } from '@nestjs-shopify/express'
import { ApolloDriver, ApolloDriverConfig } from '@nestjs/apollo'
import { Module } from '@nestjs/common'
import { ConfigModule, ConfigService } from '@nestjs/config'
import { APP_INTERCEPTOR } from '@nestjs/core'
import { GraphQLModule } from '@nestjs/graphql'
import { ApiVersion } from '@shopify/shopify-api'
import { PrismaSessionStorage } from '@shopify/shopify-app-session-storage-prisma'
import { join } from 'path'
import { AppController } from './app.controller'
import { LoggerModule } from './logger/module'
import { LoggerService } from './logger/service'
import { DesignModule } from './modules/design/module'
import { FavouriteDesignModule } from './modules/favourite-design/module'
import { PartTypeModule } from './modules/part-type/module'
import { PartModule } from './modules/part/module'
import { PrismaModule } from './modules/prisma/module'
import { PrismaService } from './modules/prisma/service'
import { StatusController } from './modules/status/status.controller'
import '@shopify/shopify-api/adapters/node'

@Module({
  imports: [
    LoggerModule,
    ConfigModule.forRoot({
      isGlobal: true,
      // TODO: add validation
      validate: a => a,
      cache: true,
      load: [configuration],
    }),
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      context: ({ req, res }) => {
        return { req, res }
      },
      autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
      sortSchema: true,
      playground: false,
      csrfPrevention: true,
      cache: new InMemoryLRUCache({
        // ~100MiB
        maxSize: Math.pow(2, 20) * 10,
        // 5 minutes (in seconds)
        ttl: 60 * 5,
      }),
      buildSchemaOptions: { dateScalarMode: 'isoDate' },
      plugins: [ApolloServerPluginLandingPageLocalDefault()],
    }),
    PrismaModule,
    ShopifyExpressModule.forRootAsync({
      useFactory: async (
        _configService: ConfigService,
        prismaService: PrismaService,
      ) => ({
        apiKey: process.env.SHOPIFY_API_KEY,
        apiSecretKey: process.env.SHOPIFY_API_SECRET,
        apiVersion: ApiVersion.July24,
        scopes: ['read_inventory', 'read_products'],
        hostName: process.env.HOST,
        isEmbeddedApp: false,
        sessionStorage: new PrismaSessionStorage(prismaService),
      }),
      imports: [PrismaModule],
      inject: [ConfigService, PrismaService],
    }),
    ShopifyAuthModule.forRootAsyncOnline(AuthStrategy.TokenExchange, {
      useFactory: async () => ({
        basePath: '/api/auth',
        returnHeaders: true,
      }),
    }),
    PartModule,
    PartTypeModule,
    DesignModule,
    FavouriteDesignModule,
  ],
  controllers: [StatusController, AppController],
  providers: [
    {
      provide: APP_INTERCEPTOR,
      useClass: LoggerService,
    },

    PrismaService,
  ],
})
export class AppModule {}

```

**Comment by tolgap** [comment]
Hi @pawelkrystkiewicz,

I haven't looked into GraphQL resolvers yet for this package. I guess the main issue is with the way we expect HTTP requests in most of our classes. We do `ctx.switchToHttp()` often. This package would have to be changed to use `GqlExecutionContext.create(ctx)` if the current `ctx.getType() === 'graphql'`.

Would you be interested in opening a PR? And include some tests for it in the `integration/` folder?

**Comment by tolgap** [comment]
> It's unusable for me due to the documentation state: I have an authorized customer with an access token on fronted, and I don't know how I should execute the request (where tu put token?) so that the guards would detect it. Nowhere in docs this is mentioned.

Its unusable because I haven't added GraphQL support yet. I clearly said this in my previous message. And I have no interest in adding GraphQL support either because I haven't had the reason to.

> Also, there is no documentation on how to develop this project locally.

In the README.md there is a reference to an example application using Next.js
